name: Check for Dependency Updates

on:
  schedule:
    # At 06:00 on every Saturday
    - cron: "0 6 * * */6"
  workflow_dispatch:

jobs:
  dependency_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Dependency Updates
        run: ./gradlew dependencyUpdates --refresh-dependencies

      - name: Upload dependency update report
        uses: actions/upload-artifact@v3
        with:
          name: dependency_updates_report
          path: ./build/dependencyUpdates/

      - name: Notify on Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C03CPGWLNAX'
          slack-message: "Dependency Update Report: ${{ job.status }} \n\n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
